name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - uses: actions/cache@v1
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: python -m pip install -r dev-requirements.txt
    - run: pytest

  formatting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - run: python -m pip install black
    - run: black --check -v .
